name: Update repository's main README file

on: [push]

jobs:
  README_UPDATE:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.head_ref }}
      - name: Updating README
        run: |
          SHELL=/bin/bash
          LATEST_VERSION=$(ls -ld -- */ | tail -1 | awk '{print $(NF)}')
          LATEST_VERSION=${LATEST_VERSION%?}
          echo "LATEST VERSION is $LATEST_VERSION"
          sed -i -E -e "s/[0-9]+\.[0-9]+\.[0-9]+($|\.[0-9]+)*/$LATEST_VERSION/g" README.md
          if git diff-index --quiet HEAD ; then
            echo "No updates."
          else
            echo "Updated README"
            git config --global user.name 'roxbot'
            git config --global user.email 'roxbot@users.noreply.github.com'
            git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/"$GITHUB_REPOSITORY"
            git commit -am 'Updated README 🤖'
            git push origin HEAD:master
          fi
          echo "✓ Done"
